# Generated by Django 5.2.7 on 2025-11-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deportista',
            old_name='last_name',
            new_name='apellido_paterno',
        ),
        migrations.AddField(
            model_name='deportista',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='matriculas_armas/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='documentos_deportistas/'),
        ),
    ]
