# Generated by Django 5.2.7 on 2025-11-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0002_rename_last_name_deportista_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='status',
            field=models.CharField(choices=[('Pendiente de Aprobación', 'Pendiente de Aprobación'), ('Pendiente de Documentación', 'Pendiente de Documentación'), ('Activo', 'Activo'), ('Suspendido', 'Suspendido'), ('Rechazado', 'Rechazado')], default='Pendiente de Aprobación', max_length=50),
        ),
    ]
