# Generated by Django 5.2.7 on 2025-11-20 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0004_alter_participacion_unique_together_and_more'),
        ('deportistas', '0003_alter_deportista_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='es_historico',
            field=models.BooleanField(default=False, help_text='Marcado si es un registro de gestiones pasadas'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='document_type',
            field=models.CharField(choices=[('Licencia B', 'Licencia B (PDF)'), ('Carnet de Identidad', 'Carnet de Identidad (PDF)'), ('Licencia de Competencia', 'Licencia de Competencia'), ('Certificado Médico', 'Certificado Médico')], max_length=50),
        ),
        migrations.CreateModel(
            name='PrestamoArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('detalles_arma_snapshot', models.TextField(blank=True, null=True)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='deportistas.arma')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia')),
                ('deportista_prestamista', models.ForeignKey(help_text='Dueño del arma', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_realizados', to='deportistas.deportista')),
                ('deportista_receptor', models.ForeignKey(help_text='Quien se presta', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recibidos', to='deportistas.deportista')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
