# Generated by Django 5.2.7 on 2025-11-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0004_deportista_es_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='departamento_origen',
            field=models.CharField(blank=True, help_text='Ej: La Paz, Santa Cruz (Solo para invitados)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='es_invitado',
            field=models.BooleanField(default=False, help_text='Si es True, no suma al ranking local ni récords.'),
        ),
    ]
