# Generated by Django 5.2.7 on 2025-11-22 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0005_deportista_departamento_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='codigo_unico',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='departamento_origen',
            field=models.CharField(blank=True, help_text='Solo para invitados', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='es_invitado',
            field=models.BooleanField(default=False, help_text='Si es True, no suma al ranking local.'),
        ),
        migrations.AlterField(
            model_name='prestamoarma',
            name='deportista_prestamista',
            field=models.ForeignKey(help_text='Dueño', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_realizados', to='deportistas.deportista'),
        ),
        migrations.AlterField(
            model_name='prestamoarma',
            name='deportista_receptor',
            field=models.ForeignKey(help_text='Solicitante', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recibidos', to='deportistas.deportista'),
        ),
    ]
