# Generated by Django 5.2.7 on 2025-11-22 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0006_deportista_codigo_unico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='es_aire_comprimido',
            field=models.BooleanField(default=False, help_text='Si es True, no exige matrícula ni inspección.'),
        ),
        migrations.AddField(
            model_name='deportista',
            name='archivo_responsabilidad',
            field=models.FileField(blank=True, null=True, upload_to='documentos_tutor/'),
        ),
        migrations.AddField(
            model_name='deportista',
            name='tutor_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='tutor_telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='departamento_origen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='es_historico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='es_invitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documento',
            name='document_type',
            field=models.CharField(choices=[('Licencia B', 'Licencia B'), ('Carnet de Identidad', 'Carnet de Identidad'), ('Licencia de Competencia', 'Licencia de Competencia'), ('Certificado Médico', 'Certificado Médico')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prestamoarma',
            name='deportista_prestamista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_realizados', to='deportistas.deportista'),
        ),
        migrations.AlterField(
            model_name='prestamoarma',
            name='deportista_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recibidos', to='deportistas.deportista'),
        ),
        migrations.CreateModel(
            name='SolicitudActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dato', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('archivo_comprobante', models.FileField(upload_to='solicitudes_cambio/')),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportistas.deportista')),
            ],
        ),
    ]
