# Generated by Django 5.2.7 on 2025-11-22 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0007_arma_es_aire_comprimido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='departamento_origen',
            field=models.CharField(blank=True, help_text='Ej: La Paz (Solo invitados)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='es_historico',
            field=models.BooleanField(default=False, help_text='Marcado si es un registro de gestiones pasadas'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='es_invitado',
            field=models.BooleanField(default=False, help_text='Si es True, no suma al ranking local.'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='document_type',
            field=models.CharField(choices=[('Licencia B', 'Licencia B (PDF)'), ('Carnet de Identidad', 'Carnet de Identidad (PDF)'), ('Licencia de Competencia', 'Licencia de Competencia'), ('Certificado Médico', 'Certificado Médico')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prestamoarma',
            name='deportista_prestamista',
            field=models.ForeignKey(help_text='Dueño del arma', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_realizados', to='deportistas.deportista'),
        ),
        migrations.AlterField(
            model_name='prestamoarma',
            name='deportista_receptor',
            field=models.ForeignKey(help_text='Quien se presta', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recibidos', to='deportistas.deportista'),
        ),
    ]
