# Generated by Django 5.2.7 on 2025-11-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0008_alter_deportista_departamento_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='force_password_change',
            field=models.BooleanField(default=True, help_text='Obliga a cambiar la contraseña en el primer login'),
        ),
    ]
