# Generated by Django 5.2.7 on 2025-11-20 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0002_juez_user'),
        ('deportistas', '0002_rename_last_name_deportista_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateField()),
                ('es_actual', models.BooleanField(default=True)),
                ('antecesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencias.record')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.categoria')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia')),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportistas.deportista')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.modalidad')),
            ],
        ),
    ]
