# Generated by Django 5.2.7 on 2025-11-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0004_alter_participacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='categorias',
            field=models.ManyToManyField(related_name='competencias', through='competencias.CategoriaCompetencia', to='competencias.categoria'),
        ),
    ]
