# Generated by Django 5.2.7 on 2025-11-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0005_competencia_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(help_text='Ej: Pago Jueces, Compra Blancos', max_length=200),
        ),
    ]
