# Generated by Django 5.2.7 on 2025-11-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0006_alter_gasto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='archivo_convocatoria',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='hora_competencia',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='numero_convocatoria',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='competencia',
            name='resultados_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resultados_competencias/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='carril',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='grupo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10),
        ),
        migrations.DeleteModel(
            name='CompetenciaJuez',
        ),
    ]
