# Generated by Django 5.2.7 on 2025-11-22 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0007_remove_competencia_archivo_convocatoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='calibre_permitido',
            field=models.CharField(blank=True, help_text='Si se define, solo permite armas de este calibre.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='codigo_verificacion',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
