# Generated by Django 5.2.7 on 2025-11-22 06:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0008_categoria_calibre_permitido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='codigo_verificacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
