# Generated by Django 5.2.7 on 2025-11-22 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0009_alter_resultado_codigo_verificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='archivo_convocatoria',
            field=models.FileField(blank=True, null=True, upload_to='convocatorias/'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='hora_competencia',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencia',
            name='numero_convocatoria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='calibre_permitido',
            field=models.CharField(blank=True, help_text="Ej: '9mm'. Si se define, filtra las armas.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='carril',
            field=models.IntegerField(default=0, help_text='Número de Puesto/Carril'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión/Pago'), ('APROBADA', 'Aprobada e Inscrita'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='grupo',
            field=models.IntegerField(default=1, help_text='Número de Grupo/Squad'),
        ),
        migrations.CreateModel(
            name='CompetenciaJuez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.juez')),
            ],
            options={
                'unique_together': {('competencia', 'juez')},
            },
        ),
    ]
