# Generated by Django 5.2.7 on 2025-11-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0010_competencia_archivo_convocatoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='es_descalificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultado',
            name='motivo_descalificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
